name: Upload Build to S3

on:
  workflow_call:
    inputs:
      s3_bucket:
        required: true
        type: string
      s3_folder:
        required: true
        type: string
      cloudfront_distribution_id:
        required: true
        type: string
      invalidate_paths:
        required: true
        type: string

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload Build.loader.js
        run: |
          aws s3 cp Build/Build.loader.js \
          s3://${{ inputs.s3_bucket }}/${{ inputs.s3_folder }}/Build/Build.loader.js

      - name: Upload Build.framework.js.unityweb
        run: |
          aws s3 cp Build/Build.framework.js.unityweb \
          s3://${{ inputs.s3_bucket }}/${{ inputs.s3_folder }}/Build/Build.framework.js.unityweb

      - name: Upload Build.data.unityweb
        run: |
          aws s3 cp Build/Build.data.unityweb \
          s3://${{ inputs.s3_bucket }}/${{ inputs.s3_folder }}/Build/Build.data.unityweb

      - name: Upload Build.wasm.unityweb
        run: |
          aws s3 cp Build/Build.wasm.unityweb \
          s3://${{ inputs.s3_bucket }}/${{ inputs.s3_folder }}/Build/Build.wasm.unityweb

      - name: Upload index.html
        run: |
          aws s3 cp index.html \
          s3://${{ inputs.s3_bucket }}/${{ inputs.s3_folder }}/index.html

      - name: CloudFront Invalidation
        run: |
          aws cloudfront create-invalidation \
          --distribution-id ${{ inputs.cloudfront_distribution_id }} \
          --paths ${{ inputs.invalidate_paths }}

      - name: Discord Notification
        if: always()
        run: |
          WEBHOOK_URL="https://discord.com/api/webhooks/1433719872063275108/ycFXIhb82-rI3pOMAJFMRgpMD72xadJJzW-t_3UohOZ_6bDIdLsIUOdX5_hxGA0oKvE_"

          STATUS="${{ job.status }}"
          COLOR=3066993
          TITLE="S3 Upload Successful"

          if [ "$STATUS" != "success" ]; then
            COLOR=15158332
            TITLE="S3 Upload Failed"
          fi

          PAYLOAD=$(cat <<EOF
{
  "username": "Deploy Bot",
  "embeds": [{
    "title": "$TITLE",
    "color": $COLOR,
    "fields": [
      { "name": "S3 Bucket", "value": "${{ inputs.s3_bucket }}" },
      { "name": "S3 Folder", "value": "${{ inputs.s3_folder }}" },
      { "name": "CloudFront ID", "value": "${{ inputs.cloudfront_distribution_id }}" },
      { "name": "Triggered By", "value": "${{ github.actor }}" }
    ]
  }]
}
EOF
)

          curl --fail -H "Content-Type: application/json" \
          -X POST \
          -d "$PAYLOAD" \
          "$WEBHOOK_URL"
